repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      exclude: .*\.(robot)
      args: [--max-line-length=120,--exclude=__init__.robot]
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: .*\.(robot)
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
      exclude: .*\.(robot)
      args: [--line-length=120]
      language_version: python3.9
